addSbtPlugin("org.scala-native" % "sbt-crossproject"         % "0.2.0")
addSbtPlugin("org.scala-native" % "sbt-scala-native"         % "0.3.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages" % "0.5.4")
addSbtPlugin("io.spray" % "sbt-boilerplate" % "0.6.0")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
